### ISSUE TITLE
 Must Initialize Fabric before using singleton()

### ISSUE THREAD

**Issue by arhmnsh** [JeanLebrument/react-native-fabric-digits#10]
Hi Guys!
I'm getting this error when I tap on the Login button.
It works fine on the iOS side.
cc: @jpdriver 

<img width="454" alt="screen shot 2016-05-14 at 8 20 04 am" src="https://cloud.githubusercontent.com/assets/1363724/15266416/e85004f6-19ac-11e6-9d03-0031aa3b533c.png">

**Comment by cpsiaki** [comment]
arhmnsh,

What was the issue with this? I can't figure it out. Did you close it because you fixed it?
