### ISSUE TITLE
Is this a typo in README?

### ISSUE THREAD

**Issue by lsps9150414** [JeanLebrument/react-native-fabric-digits#13]
In android/app/build.gradle

dependencies {
  compile fileTree(dir: 'libs', include: ['*.jar'])
  compile 'com.android.support:appcompat-v7:23.0.0'
  compile 'com.facebook.react:react-native:0.14.+'
  compile project(':react-native-digits')   < == Add this
}

---

Should that be 'react-native-fabric-digits' ?

**Comment by jpdriver** [comment]
fixed in https://github.com/JeanLebrument/react-native-fabric-digits/pull/15
