### ISSUE TITLE
[Android] Attempt to invoke virtual method 'void com.digits.sdk.android.Digits.setTheme(int)' on a null object reference

### ISSUE THREAD

**Issue by lsps9150414** [JeanLebrument/react-native-fabric-digits#17]
[Android] Seeing this when navigating to the login button scene:
![2016-06-04 12 25 20](https://cloud.githubusercontent.com/assets/5022617/15785724/5e67db5c-29eb-11e6-9a4f-60d174348ed3.png)

react-native @ 0.25.

Any idea what the problem might be?

**Comment by i-tu** [comment]
Following https://fabric.io/kits/android/digits/install, "Kit Initialization" in particular, solved this issue for me.
