### ISSUE TITLE
Installation README refers to other repo

### ISSUE THREAD

**Issue by deoqc** [JeanLebrument/react-native-fabric-digits#19]
In the README, it's referred to other repo: `npm install proximaio/react-native-fabric-digits --save`

Is it right (may its some stable version)? Or should I  `npm install JeanLebrument/react-native-fabric-digits --save` (as I did)?

**Comment by JeanLebrument** [comment]
Fixed! Thanks!

**Comment by deoqc** [comment]
Thank you
