### ISSUE TITLE
[Cancel] Crash on cancel during process

### ISSUE THREAD

**Issue by JonathanWi** [JeanLebrument/react-native-fabric-digits#9]
Hey Jean,

I'm having an issue with your component: When trying to cancel during the process, I'm prompted with this : 

![slack for ios upload](https://cloud.githubusercontent.com/assets/1074479/15216349/096cdad0-1857-11e6-9436-6a49e8be1dc8.jpg)

Any idea on how to fix it?

Thanks a lot

**Comment by jpdriver** [comment]
hey @JonathanWi -- what stage are you cancelling at? before or after you put the phone number in?

i had a go at replicating but was unable to -- so any more info you can provide would be useful. which version of the package are you using?

**Comment by senthilsivanath** [comment]
@JonathanWi  -- Kindly mention your react-native-fabric-digits version

**Comment by JonathanWi** [comment]
Sorry guys, realized that the npm install was not targeting the right package.. We can close this!
